### ISSUE TITLE
Campaign Images

### ISSUE THREAD

**Issue by phemmylintry** [obidient/23ForObiApi#10]
## Model
https://github.com/obidient/23ForObiApi/blob/e63054d6c6f598250528fbfebb484d8418f28663/models/campaign_models.py#L12-L20

## Tasks

- [ ] Create schemas for campaign images
- [ ] add campaign image, CREATE
- [ ] GET campaign image for state, {state_id}, passed as parameter

**Comment by samsoft00** [comment]
Hi @phemmylintry kindly assign this to me.
